Fix channel CMD_SIGN
ACINQ/eclair pull request #1556
Opened 2020-10-09 17:27 UTC by t-bast

We're sending the type instead of sending an instantiated class...

2020-10-09 17:34 UTC, pm47 commented
Definitely need to fix imo.

2020-10-09 17:54 UTC, pm47 reviewed
I think adding a `bob2alice.expectMsgType[CommitSig]` right after this line: https://github.com/ACINQ/eclair/blob/50363569c771afd9e617cb6f7d98ccac34a72911/eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala#L472

would make the test catch this bug.

2020-10-12 07:06 UTC, t-bast commented
> Definitely need to fix imo.

Done in the last commit.

2020-10-12 08:14 UTC, pm47 requested changes
You are missing one:

```diff
diff --git a/eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala b/eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala
index 34b358027..7722f34af 100644
--- a/eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala
+++ b/eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala
@@ -107,7 +107,7 @@ class ChannelPaneController(val channelRef: ActorRef, val peerNodeId: String) ex
             """.stripMargin, ButtonType.YES, ButtonType.NO)
         alert.showAndWait
         if (alert.getResult eq ButtonType.YES) {
-          channelRef ! CMD_FORCECLOSE
+          channelRef ! CMD_FORCECLOSE(ActorRef.noSender)
         }
       }
     })
```

regex: `CMD_[a-zA-Z_]+(?=\s)`

2020-10-12 08:40 UTC, pm47 approved these changes

2020-10-12 08:42 UTC, merged