Make db migration code less footgunny
ACINQ/eclair pull request #2823
Opened 2024-02-15 13:32 UTC by pm47

Using a range of versions instead of enumerating each version saves us from having to update the condition everytime. It is easy to miss as we don't test every migration combinations.

Fixes a regression caused by #2705 reported by @fishcakeday.

2024-02-15 13:49 UTC, thomash-acinq commented
I actually think that the previous version is less footgunny. If we forget to update the migration code, it fails when starting the database but nothing bad happens, no data corruption. However with this change, if we ever forget to update the migration code, there will be no warning before we corrupt the database.

2024-02-15 13:52 UTC, pm47 commented
> I actually think that the previous version is less footgunny. If we forget to update the migration code, it fails when starting the database but nothing bad happens, no data corruption. However with this change, if we ever forget to update the migration code, there will be no warning before we corrupt the database.

That is a good point. I'm going to open a 2nd PR that simply fixes the regression, and leave this one open for further discussion.

2024-02-16 07:54 UTC, t-bast reviewed
I think @thomash-acinq is right, this makes it less likely to forget to update this part, but the consequences are worse if we forget to also write migration code...but I don't see yet a good solution to ensure that a migration function is added and correctly called, apart from requiring migration unit tests every time we add a new version.

2024-02-16 11:20 UTC, remyers approved these changes
This looks like sensible foot protection.

2024-02-16 11:22 UTC, remyers requested changes
Removing my approval - I missed @thomash-acinq comment and agree this could use some further thought.

2024-02-16 12:20 UTC, pm47 commented
There is clear consensus, closing the PR.

2024-02-16 12:20 UTC, closed without merging