Use final spec values for splicing
ACINQ/eclair pull request #2887
Opened 2024-07-23 09:07 UTC by t-bast

We replace our experimental version of `splice_init`, `splice_ack` and `splice_locked` by their official version (see https://github.com/lightning/bolts/pull/1160). If our peer is using the experimental feature bit, we convert our outgoing messages to use the experimental encoding and incoming messages to the official messages.

We also change the TLV fields added to `tx_add_input`, `tx_signatures` and `splice_locked` to match the spec version. We always write both the official and experimental TLV to updated nodes (because the experimental one is odd and will be ignored) but we drop the official TLV if our peer is using the experimental feature, because it won't understand the even TLV field.

This guarantees backwards-compatibility with peers who only support the experimental feature.

@ddustin you should be able to start cross-compat tests based on this branch. Note that we currently only support unannounced channels (we haven't implemented the gossip part yet) and don't support RBF (but it will be added in another commit to this PR).

2024-08-13 13:46 UTC, remyers commented
This is an observation that occurred to me while reviewing this PR that might be relevant for a future PR ..

There will be times when using `CMD_BUMP_FUNDING_FEE` instead of `CMD_SPLICE` would cost less on-chain and confirm faster if you want to perform an additional splice while a pending splice is unconfirmed. The total cost to create a new funding transaction with `CMD_SPLICE` will often be higher than making the same changes with `CMD_BUMP_FUNDING_FEE` at a slightly higher fee rate. If you are blocked from making a new splice because a pending splice has been fee bumped, you could also make a new fee bump to splice in/out value rather than waiting for the previously rbf'd splice to confirm.

This seems to be technically possible in the protocol because CMD_BUMP_FUNDING_FEE uses the interactive tx protocol and can change the funding contribution with the `funding_output_contribution` TLV. Figuring out if a splice or rbf-splice is cheaper will also need to consider the additional fees paid to bump our counter party's inputs and outputs.

Perhaps the biggest downside I can see (beside complexity) is that if your pending splice or rbf confirms before a rbf-splice, then you would need to renegotiate it as a new splice.

Am I missing something here wrt fee savings? Do you think it would be worth considering this situation now rather than later?

2024-08-13 14:03 UTC, t-bast commented
> Perhaps the biggest downside I can see (beside complexity) is that if your pending splice or rbf confirms before a rbf-splice, then you would need to renegotiate it as a new splice.

Yes, the main reason we're not providing this yet (even though this is in theory possible) is to manage complexity. It can get really complex very quickly once you start going down that road, because if each splice "part" maps to a specific action (an on-the-fly funding), it can be a huge mess to reconcile which parts where actually done and which parts need to be replayed if a previous RBF attempt confirms.

2024-08-21 17:26 UTC, remyers requested changes
Looks good - the refactor for RBF makes it easier to read/understand.

I found a few nits but main issues to take a look at are related to adding logic to reject an TxInitRbf or SpliceInit when the parent splice is unconfirmed.

2024-08-21 17:26 UTC, remyers commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
>              log.info(s"accepting splice with remote.in.amount=${msg.fundingContribution} remote.in.push=${msg.pushAmount}")
If 0-conf is activated, should we still only allow a limited number of previous unconfirmed parent txs? and/or have some sort of rate limit on?  or perhaps it doesn't matter if we already trust our peer enough to activate 0-conf..

2024-08-22 12:54 UTC, remyers commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4.scala
>          ("deferred" | optional(bool8, lengthDelimited(channelReadyCodec)))).as[DATA_WAIT_FOR_DUAL_FUNDING_CONFIRMED]
Ah! I see, it only actually reads/writes 0x01 or 0x02 in dualFundingStatusCodec to indicate if the state is waiting for sigs or waiting for confirmation.

2024-08-27 13:38 UTC, remyers commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
>            } else {
Looks good!

2024-08-29 12:55 UTC, remyers requested changes
Changes to tests to disallow sequences of unconfirmed splices looks good. I only had a few minor nits/questions.

2024-09-02 11:51 UTC, remyers commented on eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala
>      bob2alice.ignoreMsg { case _: ChannelUpdate => true }
Ohh, I see. Its used before you do the disconnect/reconnect sequence.

2026-03-05 17:48 UTC, t-bast commented
Claude's review regarding backwards-compatibility with the previous protocol:

```
After reviewing all changes, the backwards-compatibility logic is correct. Key observations:

 1. TLV tag 1 size discrimination (ChannelTlv.scala:276-281): Works correctly -- 32 bytes = legacy, 33 bytes = official. The retransmitCommitSig flag is safely ignored for legacy (always false).
 2. ChannelReestablish accessor fallback logic (LightningMessageTypes.scala:215-225):
   - nextFundingTxId_opt: Correctly checks official tag 1 first, falls back to ExperimentalNextFundingTlv (tag 0). When tag 1 is legacy (32 bytes), it falls through to tag 0 as expected.
   - myCurrentFundingLocked_opt: Correctly checks official MyCurrentFundingLockedTlv (tag 5) first, falls back to ExperimentalMyCurrentFundingLockedTlv (tag 3).
   - yourLastFundingLocked_opt: Only populated when tag 1 is legacy (not official). Correct -- removed from official protocol.
   - retransmitAnnSigs: Only available from tag 5 (official). Legacy peers always get false, which is correct since they use splice_locked echo instead.
 3. PeerConnection message conversion (PeerConnection.scala:209-224): Correctly converts SpliceInit/Ack/Locked between experimental (37000/37002/37004) and official (80/81/77) types. TLV filtering
 correctly strips official-only TLVs (SharedInputTxId tag 0, PreviousFundingTxSig tag 0) while leaving experimental TLVs (tags 1105, 601). CommitSigBatch correctly uses StartBatch for official peers and
 inline ExperimentalBatchTlv for legacy.
 4. Channel reestablish sending (Channel.scala:2417-2560): Clean bifurcation based on useLegacySpliceProtocol. Legacy sends tag 0 + tag 1 (32 bytes) + tag 3. Official sends tag 1 (33 bytes) + tag 5. Both
 sets of TLVs are mutually exclusive and correct.
 5. Retransmission logic (Channel.scala:2606-2609, 3485-3491): Legacy uses nextLocalCommitmentNumber == remoteCommitIndex (implicit signal). Official uses retransmitInteractiveTxCommitSig (explicit flag).
 Both paths are consistent with their protocol's semantics.
 6. nextLocalCommitmentNumber computation (InteractiveTxBuilder.scala:1214-1217): Legacy rolls back to unsignedCommit.index to signal "haven't received commit_sig". Official always uses localCommitIndex +
 1 and relies on the explicit flag. Correct.
 7. resendSpliceLockedIfNeeded (Channel.scala:3542-3556): Only retransmits for legacy peers. Official peers don't need this because MyCurrentFundingLockedTlv (tag 5) already signals the locked state.
 8. resendChannelReadyIfNeeded (Channel.scala:3452-3483): Always retransmits for legacy peers. Official peers follow the standard spec condition. Correct.

 No bugs or correctness issues found.
```

2026-04-29 12:40 UTC, pm47 commented on eclair-core/src/test/scala/fr/acinq/eclair/io/OpenChannelInterceptorSpec.scala
> +    val features = defaultFeatures.add(Features.Splicing, FeatureSupport.Optional).add(Features.OnTheFlyFunding, FeatureSupport.Optional)
To ease rebase on feature branches:
```suggestion
    val features = defaultFeatures
      .add(Features.Splicing, FeatureSupport.Optional)
      .add(Features.OnTheFlyFunding, FeatureSupport.Optional)
```

2026-04-29 12:40 UTC, pm47 commented on eclair-core/src/test/scala/fr/acinq/eclair/io/OpenChannelInterceptorSpec.scala
> +    val features = defaultFeatures.add(Features.Splicing, FeatureSupport.Optional).add(Features.OnTheFlyFunding, FeatureSupport.Optional)
```suggestion
    val features = defaultFeatures
      .add(Features.Splicing, FeatureSupport.Optional)
      .add(Features.OnTheFlyFunding, FeatureSupport.Optional)
```

2026-04-29 12:46 UTC, t-bast commented on eclair-core/src/test/scala/fr/acinq/eclair/io/OpenChannelInterceptorSpec.scala
> +    val features = defaultFeatures.add(Features.Splicing, FeatureSupport.Optional).add(Features.OnTheFlyFunding, FeatureSupport.Optional)
Done in https://github.com/ACINQ/eclair/pull/2887/commits/668becb06a7b7dc3e19a22b8cae00de097f1ee62

2026-04-29 12:47 UTC, t-bast commented on eclair-core/src/test/scala/fr/acinq/eclair/io/OpenChannelInterceptorSpec.scala
> +    val features = defaultFeatures.add(Features.Splicing, FeatureSupport.Optional).add(Features.OnTheFlyFunding, FeatureSupport.Optional)
Done in https://github.com/ACINQ/eclair/pull/2887/commits/668becb06a7b7dc3e19a22b8cae00de097f1ee62

2026-04-29 12:49 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
>      }
```scala
  def apply(channelId: ByteVector32, 
            tx: Transaction, 
            witnesses: Seq[ScriptWitness], 
            previousFundingSig_opt: Option[ChannelSpendSignature]): TxSignatures = {
    val tlvs: Set[TxSignaturesTlv] = Set(
      previousFundingSig_opt match {
        case Some(IndividualSignature(sig)) => Set(TxSignaturesTlv.PreviousFundingTxSig(sig), TxSignaturesTlv.ExperimentalPreviousFundingTxSig(sig))
        case Some(partialSig: PartialSignatureWithNonce) => Set(TxSignaturesTlv.PreviousFundingTxPartialSig(partialSig))
        case None => Set.empty
      },
    ).flatten
    TxSignatures(channelId, tx.txid, witnesses, TlvStream(tlvs))
  }
```

2026-04-29 13:03 UTC, t-bast commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
>      }
I've done something slightly differently in https://github.com/ACINQ/eclair/pull/2887/commits/318ba314d5bc9824e031d07b772c84920ccfd6ff to flatten `Option`s instead of `Set`s, which should be even easier when rebasing.

2026-04-30 09:30 UTC, pm47 approved these changes

2026-04-30 09:42 UTC, merged