Send `channel_announcement` for splice transactions on public channels
ACINQ/eclair pull request #2968
Opened 2024-12-18 15:53 UTC by t-bast

We now support splicing on public channels: once the splice transaction is confirmed and locked on both sides, nodes will exchange announcement signatures that allows them to create a `channel_announcement` that they then broadcast to the network.

This requires reworking the data model to include the announcement and the real `short_channel_id` in each commitment, which lets us cleanly distinguish real `short_channel_id`s from aliases (which are set at the channel level regardless of the current commitments).

The flow now becomes:

- when the funding transaction of a commitment confirms, we set the corresponding real `short_channel_id` in that commitment
- if the channel is public and we've received `channel_ready` or `splice_locked`, we send our `announcement_signatures`
- if we receive `announcement_signatures` for a commitment for which the funding transaction is unconfirmed, we stash it and replay it when the transaction confirms
- if we receive `announcement_signatures` for a confirmed commitment, and we don't have a more recently announced commitment, we generate a `channel_announcement`, store it with the commitment and update our router data

When creating a `channel_update` for a public channel, we always use the `short_channel_id` that matches the latest announcement we created. This is very important to guarantee that nodes receiving our updates will not discard them because they cannot match it to a channel.

For private channels, we stop allowing usage of the `short_channel_id` for routing: `scid_alias` MUST be used, which ensures that the channel utxo isn't revealed.

Note that when migrating to taproot channels, `splice_locked` will be used to transmit nonces for the announcement signatures, which will be compatible with the existing flow (and similarly, `channel_ready` will be used for the initial funding transaction). They are retransmitted on reconnection to ensure that the announcements can be generated.

Don't be scared by the large number of added lines: most of them are JSONs for backwards-compatibility serialization tests.

2025-01-10 13:16 UTC, remyers commented
I've taken a first pass and it looks good so far. I've focused mostly on the channel and router behavior; less on the serialization so far.

During a channel reestablishment it seems like we only resend announcement sigs when no announcement was sent during initial funding, but not during splices.

I also have a few questions and suggestions to add tests for a few incidental bug fixes you made during the refactor that probably don't have associated tests.

2025-01-10 13:16 UTC, remyers requested changes
I've taken a first pass and it looks good so far. I've focused mostly on the channel and router behavior; less on the serialization so far.

During a channel reestablishment it seems like we only resend announcement sigs when no announcement was sent during initial funding, but not during splices.

I also have a few questions and suggestions to add tests for a few incidental bug fixes you made during the refactor that probably don't have associated tests.

2025-01-10 13:40 UTC, remyers commented on eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
>              handleChannelUpdate(d1, db, nodeParams.currentBlockHeight, Left(lcu))
Gotcha - I was trying to think ahead to prevent a future regression.

2025-01-13 10:51 UTC, remyers commented on eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
> +          case None =>
Looks good.

2025-01-14 13:16 UTC, remyers commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4.scala
> +      .typecase(0x09, (txCodec :: provide(RealShortChannelId(0)) :: provide(Option.empty[ChannelAnnouncement]) :: optional(bool8, lengthDelimited(txSignaturesCodec)) :: optional(bool8, liquidityPurch
Oh wait! nevermind, the `DATA_WAIT_FOR_CHANNEL_READY_15_Codec` is the latest version, so it does not need to migrate. Sorry - got lost in the versioning.

2025-01-14 13:33 UTC, remyers commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4.scala
> +      .typecase(0x09, (txCodec :: provide(RealShortChannelId(0)) :: provide(Option.empty[ChannelAnnouncement]) :: optional(bool8, lengthDelimited(txSignaturesCodec)) :: optional(bool8, liquidityPurch
Also I see why we only migrate funding tx index 0. It's because before the splice version we only published the real scid of the initial funding tx.

2025-01-15 18:00 UTC, remyers commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version1/ChannelCodecs1.scala
> +      case commitments :: shortChannelId :: _ :: HNil =>
> > I believe that the lastSent attribute of DATA_WAIT_FOR_FUNDING_CONFIRMED can also be safely factored out
> 
> I don't understand what you mean, that seems unrelated, can you detail?

Yes, an unrelated observation. I just happened to discover that while investigating `lastSent` in DATA_WAIT_FOR_CHANNEL_READY. Perhaps in the next PR focused on just serialization it would be worth removing from `DATA_WAIT_FOR_FUNDING_CONFIRMED' also, but there's enough in this PR that it's not worth changing now.

2025-01-15 18:01 UTC, remyers submitted a review, later dismissed

2025-01-28 10:55 UTC, pm47 reviewed
LGTM, only nits.

2025-01-28 10:55 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
> +            log.debug("ignoring remote announcement_signatures for scid={} with fundingTxIndex={}, channel is already announced", remoteAnnSigs.shortChannelId, c.fundingTxIndex)
This log isn't entirely accurate:
```suggestion
            log.debug("ignoring remote announcement_signatures for scid={} with fundingTxIndex={}, channel is announced and local announcement_signatures  were only sent once", remoteAnnSigs.shortChannelId, c.fundingTxIndex)
```

2025-01-28 10:55 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
> +              log.info("announcing channelId={} on the network with shortChannelId={} for fundingTxIndex={}", d.channelId, localAnnSigs.shortChannelId, c.fundingTxIndex)
This log could be moved in the `else`.

2025-01-28 10:55 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
> -  def makeAnnouncementSignatures(nodeParams: NodeParams, channelParams: ChannelParams, remoteFundingPubKey: PublicKey, shortChannelId: RealShortChannelId): AnnouncementSignatures = {
`makeChannelUpdate` could also be moved to `Announcements.scala` (and it would be less ambiguous if it didn't take a full `Commitments` as input).

2025-01-28 10:55 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
> +              stay()
It could also be that `remoteAnnSigs.shortChannelId` is wrong or unexisting. I find it a little weird that the condition to add to `announcementSigsStash` and remove from it are not symmetrical:
- we stash when the related commitment is not found
- we unstash when we receive a `splice_locked` from remote.

Shouldn't we instead:
- stash when the corresponding commit exists but is not locally locked (and drop if unexisting)
- unstash when the corresponding commit gets locally locked?

2025-01-28 10:55 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
> +          localAnnSigs_opt.flatMap(ann => announcementSigsStash.get(ann.shortChannelId)).foreach(self ! _)
Just a refactoring, I find it easier to understand that way (the same could be done in the `WatchFundingConfirmedTriggered` handler):

```suggestion
          val localAnnSigs_opt = if (d.commitments.announceChannel) commitment.signAnnouncement(nodeParams, d.commitments.params) else None
          localAnnSigs_opt match {
            case Some(localAnnSigs) =>
              // The commitment was locked on our side and we were waiting to receive the remote splice_locked before sending our announcement_signatures.
              announcementSigsSent += localAnnSigs.shortChannelId
              // If we've already received the remote announcement_signatures, we're now ready to process them.
              announcementSigsStash.get(localAnnSigs.shortChannelId).foreach(self ! _)
            case None => // The channel is private or the commitment isn't locked on our side
          }
```

2025-01-28 10:55 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
> +          d.commitments.all.find(_.fundingTxIndex == 0) match {
```suggestion
          // Retransmission of local announcement_signatures for splices are done when receiving splice_locked
          d.commitments.all.find(_.fundingTxIndex == 0) match {
```

2025-01-30 09:43 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
> +  def updateRemoteFundingStatus(fundingTxId: TxId, lastAnnounced_opt: Option[AnnouncedCommitment])(implicit log: LoggingAdapter): Either[Commitments, (Commitments, Commitment)] =
I think this would be more consistent and reduce a bit the mental load of bringing the concept of announcement in this pruning logic:

```suggestion
  def updateRemoteFundingStatus(fundingTxId: TxId, lastAnnouncedFundingTxId_opt: Option[TxId])(implicit log: LoggingAdapter): Either[Commitments, (Commitments, Commitment)] =
```

2025-01-30 09:43 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4.scala
> +      .typecase(0x09, (txCodec :: provide(RealShortChannelId(0)) :: optional(bool8, lengthDelimited(txSignaturesCodec)) :: optional(bool8, liquidityPurchaseCodec)).as[ConfirmedFundingTx])
What are the side effects of putting fake real scid here?

2025-01-30 09:43 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4.scala
> +        ("shortIds" | shortids)).as[ChannelTypes4.DATA_WAIT_FOR_CHANNEL_READY_0b].xmap(d => d.migrate(), d => ChannelTypes4.DATA_WAIT_FOR_CHANNEL_READY_0b.from(d))
I think we should only provide a decoder (which will make an encoding attempt explicitly fail), and remove the `.from()` companion methods:

```suggestion
        ("shortIds" | shortids)).as[ChannelTypes4.DATA_WAIT_FOR_CHANNEL_READY_0b].map(d => d.migrate()).decodeOnly
```

2025-01-30 09:43 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
> +              stay()
> we cannot distinguish those two cases, so we have to assume it's the first one

Doh, that is the part I was missing. We don't know the local scid until it is confirmed.

2025-01-30 12:34 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4.scala
> +        ("shortIds" | shortids)).as[ChannelTypes4.DATA_WAIT_FOR_CHANNEL_READY_0b].xmap(d => d.migrate(), d => ChannelTypes4.DATA_WAIT_FOR_CHANNEL_READY_0b.from(d))
Yes, and we use this already at several places for the same purpose.

2025-01-30 12:46 UTC, pm47 approved these changes
LGTM

2025-01-30 12:46 UTC, pm47 commented on eclair-core/src/test/resources/nonreg/codecs/000003-DATA_NORMAL/funder/data.json
> +  "aliases" : {
It's a shame that `localFundingStatus` is unconfirmed in these test data, we cannot test the setting of real scid.

2025-01-30 12:46 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelTypes4.scala
> +      )
Just for fun, I know that you are not a fan of quicklens, this would be:

```scala
commitments
        .modifyAll(
          _.active.each.localFundingStatus.when[ConfirmedFundingTx].shortChannelId,
          _.inactive.each.localFundingStatus.when[ConfirmedFundingTx].shortChannelId
      ).setToIfDefined(shortIds.real_opt)
```

2025-01-30 13:03 UTC, merged