Rework channel announcement signatures handling
ACINQ/eclair pull request #2969
Opened 2024-12-19 09:36 UTC by t-bast

Now that we wait for at least 6 confirmations before considering a channel confirmed, we can simplify our channel announcement logic. Whenever a channel reaches the confirmed state, it can be announced to the network (if nodes wish to announce it). We thus don't need the "deeply buried" state and the "temporary" scid anymore.

The logic is much simpler to follow: when the channel confirms, we internally update the real scid to match the confirmed funding tx and send our `announcement_signatures`. When we receive our peer's `announcement_signatures`, we stash them if the funding tx doesn't have enough confirmations yet, otherwise we announce the channel and create a new `channel_update` that uses the real scid.

Whenever we create a `channel_update`, we simply look at whether the channel is announced or not to choose which scid to use.

This will make it much simpler to announce splice transactions, which don't need a "deeply buried" state either and will instead simply rely on whether the splice transaction is confirmed or not to generate `announcement_signatures`.

2025-01-07 19:37 UTC, remyers requested changes
Looks like a nice simplification for annoucement signatures. I only have a few nits and suggestions so far. I've reviewed it all line by line but will spend some time tomorrow to go back through and review the tests again in more detail to see if I can find anything that might be missing.

2025-01-08 09:17 UTC, remyers commented on eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
> +  test("recv WatchFundingConfirmedTriggered (public channel, zero-conf)", Tag(ChannelStateTestsTags.ChannelsPublic), Tag(ChannelStateTestsTags.AnchorOutputsZeroFeeHtlcTxs), Tag(ChannelStateTestsTags.
Ah, I understand now that the missing tests were for when in the `Normal` state but only relevant when waiting for `WatchFundingDeeplyBuriedTriggered` which is now removed. So the tests I thought were missing are just in the other `WaitForFunding...` specs.

2025-01-08 10:21 UTC, remyers commented on eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
> +    if (interceptChannelUpdates && !tags.contains(ChannelStateTestsTags.ChannelsPublic)) {
Looks good; a better name and more complete!

2025-01-08 10:23 UTC, remyers approved these changes
LGTM!

2025-01-27 11:15 UTC, pm47 commented on eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
> +                announcementSigsSent += remoteAnnSigs.shortChannelId
Why do we increment `announcementSigsSent` here? We are not sending our `localAnnSigs` AFAICT?

2025-01-27 13:05 UTC, pm47 approved these changes

2025-01-27 13:31 UTC, merged